services:
  nerf-ann:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GPU_ARCH: ${GPU_ARCH:-86}
    image: gan-nerf-project:latest
    container_name: nerf-ann-paper
    ipc: host 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    volumes:
      - ./assets/data:/workspace/assets/data
      - ./assets/logs:/workspace/assets/logs
      - ./src:/workspace/src
      - ./src/nerf/PixelNeRFModel.py:/workspace/.venv/lib/python3.11/site-packages/PixelNeRFModel.py
      - ./main.py:/workspace/main.py
    environment:
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
      - IS_DOCKER=1
    stdin_open: true
    tty: true
    command: python main.py
