[project]
name = "nerf-ann-paper"
version = "0.0.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "lpips>=0.1.4",
    "matplotlib>=3.10.8",
    "nerfstudio @ git+https://github.com/felipe-gsilva/nerfstudio",
    "numpy>=2.2.6",
    "scikit-image>=0.25.2",
    "scikit-learn>=1.7.2",
    "torch>=2.11.0",
    "torchmetrics>=1.9.0",
    "tqdm>=4.67.3",
    "pillow>=12.2.0",
    # models
    "merf @ git+https://github.com/felipe-gsilva/merfstudio",
    "nerfstudio-gnt",
    "nerfstudio-pixelnerf"
]


[tool.uv.sources]
torch = [
    { index = "pytorch-cu124" },
]
torchvision = [
    { index = "pytorch-cu124" },
]

[[tool.uv.index]]
name = "pytorch-cu124"
url = "https://download.pytorch.org/whl/cu124"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu113"
url = "https://download.pytorch.org/whl/cu113"
explicit = true

[tool.uv.extra-build-dependencies]
nerfstudio = ["setuptools>=61", "wheel"]
