[project]
name = "nerf-ann-paper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "lpips>=0.1.4",
    "matplotlib>=3.10.8",
    "nerfstudio @ git+https://github.com/felipe-gsilva/nerfstudio",
    "numpy>=2.2.6",
    "scikit-image>=0.25.2",
    "scikit-learn>=1.7.2",
    "torch>=2.11.0",
    "torchmetrics>=1.9.0",
    "tqdm>=4.67.3",
    "pillow>=12.2.0",
    "nerfstudio-gnt",
    "nerfstudio-pixelnerf"
]
